[build]
provider = "python"
version = "3.10.12"

[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y python3.10 python3-pip libglib2.0-0 libsm6 libxrender1 libxext6",
]

[phases.install]
cmds = [
    "pip3 install -r requirements.txt",
    "npm install",
]

[start]
cmd = "node server.js"