[build]
builder = "nixpacks"

[deploy]
startCommand = "python app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.environment]
PYTHON_VERSION = "3.10.12"

[deploy.environment]
SESSION_TYPE = "filesystem"
SESSION_FILE_DIR = "/tmp/flask_session"  # Usa /tmp que es escribible en Railway